Import('TOOL_ROOT')
from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
""")



CPPDEFINES = ['RTK_HAL_DRIVER']
if GetDepend(['CONFIG_REALTEK_BSP_FLASH']):
    src += ['drv_flash.c']
    CPPDEFINES += ['RTK_HAL_FLASH']

if GetDepend(['CONFIG_REALTEK_BSP_DLPS']):
    src += ['drv_dlps.c']
    CPPDEFINES += ['RTK_HAL_DLPS']

if GetDepend(['CONFIG_REALTEK_BSP_SPI']):
    src += ['drv_spi.c']
    CPPDEFINES += ['RTK_HAL_SPI']


if GetDepend(['CONFIG_REALTEK_BSP_UART']):
    src += ['drv_uart.c']
    CPPDEFINES += ['RTK_HAL_UART']

if GetDepend('CONFIG_REALTEK_BSP_I2C'):
    src += ['drv_i2c.c']
    CPPDEFINES += ['RTK_HAL_I2C']

if GetDepend(['RT_USING_ADC']):
    src += Glob('drv_adc.c')
    CPPDEFINES += ['RTK_HAL_ADC']

if GetDepend(['RT_USING_DAC']):
    src += Glob('drv_dac.c')
    CPPDEFINES += ['RTK_HAL_DAC']

if GetDepend('CONFIG_REALTEK_BSP_LCD') or GetDepend(['CONFIG_REALTEK_LCD']):
    src += ['drv_lcd.c']
    CPPDEFINES += ['RTK_HAL_LCD']

if GetDepend('CONFIG_REALTEK_BUILD_VG_LITE'):
    src += ['drv_gpu.c']
    CPPDEFINES += ['RTK_MODULE_VG_LITE']

if GetDepend('CONFIG_REALTEK_MODULE_RTK_PPE'):
    CPPDEFINES += ['RTK_MODULE_RTK_PPE']

if GetDepend(['CONFIG_REALTEK_BSP_SDIO']):
    src += ['drv_sdio.c']
    CPPDEFINES += ['RTK_HAL_SDIO']

if GetDepend(['CONFIG_REALTEK_BSP_USBD']):
    src += ['drv_usbd.c']
    CPPDEFINES += ['RTK_HAL_USBD']

if GetDepend(['CONFIG_REALTEK_BSP_USBH']):
    src += ['drv_usbh.c']
    CPPDEFINES += ['RTK_HAL_USBH']

if GetDepend(['CONFIG_REALTEK_BSP_TOUCH']) or GetDepend(['CONFIG_REALTEK_BSP_GPIO']):
    src += ['drv_gpio.c']
    CPPDEFINES += ['RTK_HAL_GPIO']

if GetDepend(['CONFIG_REALTEK_BSP_TOUCH']):
    src += ['drv_touch.c']
    CPPDEFINES += ['RTK_HAL_TOUCH = "1"']

if GetDepend(['CONFIG_REALTEK_BSP_ONCHIP_RTC']):
    src += ['drv_rtc.c']
    CPPDEFINES += ['RTK_HAL_RTC']
path =  [cwd]


group = DefineGroup('hal_drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
